version: '3'
services:
  soffy_node:
    build:
      context: .
      dockerfile: Dockerfile
    image: bitcoind_node
    volumes:
      - soffy_data:/root/.bitcoin/blocks
    tty: true

  harry_node:
    image: bitcoind_node
    volumes:
      - harry_data:/root/.bitcoin/blocks
    tty: true

volumes:
  soffy_data:
  harry_data: